### ISSUE TITLE
error after installing v0.3.12

### ISSUE THREAD

**Issue by Cadsters** [floris-b/lms_tts_notify#10]
After installing v0.3.12 i get this error in my log:

`Uncaught thread exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/lms_tts_notify/__init__.py", line 126, in run
    self.save_state()
  File "/config/custom_components/lms_tts_notify/__init__.py", line 298, in save_state
    attributes['query_result']['_p2'] = 0
KeyError: 'query_result'
`
I'v restarted several times but still the same error. I reverted to v0.3.11 and everything works.

**Comment by floris-b** [comment]
Should be fixed in v0.3.13
