### ISSUE TITLE
issue percists in v0.3.13

### ISSUE THREAD

**Issue by Cadsters** [floris-b/lms_tts_notify#11]
Thanks for responding so quickly but it is still not fixed.
``
Deze fout is ontstaan door een aangepaste integratie.

Logger: root
Source: custom_components/lms_tts_notify/__init__.py:432
Integration: LMS TTS Notify (documentation, issues)
First occurred: 11:21:44 (1 occurrences)
Last logged: 11:21:44

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/lms_tts_notify/__init__.py", line 432, in run
    if ( not home or home.state == 'home' or self.force_play ) and silent.state=='off':
AttributeError: 'NoneType' object has no attribute 'state'
``

**Comment by Cadsters** [comment]
Thanks!  v.0.3.14 fixed the issue.
