### ISSUE TITLE
Playlist saved but no announcement

### ISSUE THREAD

**Issue by CaptainKarma** [floris-b/lms_tts_notify#2]
Hi,

Trying to configure notify and a test it flashes up on the LMS player screen but no announcement is made.  Here is the error in the log, not sure what to change. 

I have force play set in the automation

Thanks

`2021-07-27 12:57:22 INFO (MainThread) [homeassistant.components.automation.new_automation] New Automation: Executing step call service
2021-07-27 12:57:22 DEBUG (MainThread) [custom_components.lms_tts_notify] Received on event bus: {'entity_id': 'media_player.office', 'message': 'testing', 'force_play': True, 'volume': 0.3}
2021-07-27 12:57:22 DEBUG (Coordinator) [custom_components.lms_tts_notify] Save state: media_player.office -> {'state': 'playing', 'attributes': {'sync_group': [], 'volume_level': 0.27, 'media_position': 12, 'repeat': '0'}}
2021-07-27 12:57:22 DEBUG (Coordinator) [custom_components.lms_tts_notify] Save playlists: media_player.office
2021-07-27 12:57:22 DEBUG (Coordinator) [custom_components.lms_tts_notify] UnSync media_player.office
2021-07-27 12:57:22 ERROR (office_queue) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/config/custom_components/lms_tts_notify/__init__.py", line 403, in run
home = self._hass.states.get(self._device_group).state
AttributeError: 'NoneType' object has no attribute 'state'`

**Comment by floris-b** [comment]
Your device_group is not a valid entity

**Comment by floris-b** [comment]
fixed in v0.3.9
